### ISSUE TITLE
Formatter doesnt seem to work

### ISSUE THREAD

**Issue by franroa** [mistweaverco/kulala-fmt#3]
The image shows the following:
- First cat on a bad formatted http file
- A run on kulala-fmt: it seems to find a bad formatted file
- Another cat to the file: nothing changed (except a new line at the end of the file)
- A new run on kulala-fmt
- It acknowledge the file as correct

![kulala](https://github.com/user-attachments/assets/cd9292cf-f5c6-467d-8d84-f6333553c262)

**Comment by gorillamoe** [comment]
It does work, but not as intended I guess :+1: 

Thanks for your findings!

At the current state it just makes sure, that it finds a request like `GET url [version]` and that there is the correct syntax like

```
request
headers

body
```

Then it just makes sure that the delimiters like `###` are set correctly and that all comments are above the `request`. Also it makes sure that the httpYak alike Metadata is put after the headers section and before the body.

But you're right, it should remove the whitespace "around" headers.

Maybe even enforce a good habit of lowercasing all header "keys".

About formatting the body.. idk how I feel about this :shrug: 

If we have a discussion up that gets enough votes I will implement a auto-format body asap :+1: 

Thanks for your contribution!

**Comment by gorillamoe** [comment]
Let's get this over to this discussion here: https://github.com/mistweaverco/kulala-fmt/discussions/5
